### ISSUE TITLE
possible match function errors

### ISSUE THREAD

**Issue by jeekinlau** [jendelman/diaQTL#15]
I think there may be a possible issue in one of the match functions in read_data because if I put in a phenotype file that is not sorted alphabetically by the genotype column, the QTL which I know are there disappear. Then if I feed a file with sorted by genotype column the QTL which I know exists re-appears.

**Comment by jendelman** [comment]
This error occurred because the first column of the phenotype file was not named "id", and the software did not check for this. The column is now renamed internally to prevent the problem from occurring. Thank you for catching this issue!
