### ISSUE TITLE
fitQTL error

### ISSUE THREAD

**Issue by jeekinlau** [jendelman/diaQTL#16]
Hi Jeff and Rodrigo,

The fitQTL function might be broken. I tried with the vignette data I think this may be the problem:

In vignette models that have markers with dominance=1 creates this error:

` fit1 <- fitQTL(data=data, trait="tuber_shape", params=params, qtl=model1)
Error in fitQTL(data = data, trait = "tuber_shape", params = params, qtl = model1) : 
  object 'digenic.effects' not found`

I think what is happening is a couple of commits ago the the digenic.effects matrix was not inside the dominance>1 if statement.

https://github.com/jendelman/diaQTL/blob/3db8eb7f70e1b6200e8516146620c4d137135fe9/R/fitQTL.R#L189-L196

Thanks!

Jeekin Lau
Postdoctoral Research Associate
Horticultural Sciences, Texas A&M University

**Comment by jendelman** [comment]
Jeekin,
Thank you for catching this mistake. I was lazy and should have run the vignette after attempting to fix the error in v1.02. I believe it is fixed now.

Jeff
